/*
 * Stub pm_config.h for spi_dfu unit tests.
 * Provides the partition-manager constants that spi_dfu.c references.
 * The real file is generated by the build system from pm_static_*.yml.
 */
#pragma once

/* Provided via CMake -D flags in the test's CMakeLists.txt */
/* PM_NRF5340_DFU_ID and PM_NRF5340_DFU_SIZE come from there. */

#ifndef PM_NRF5340_DFU_ID
#define PM_NRF5340_DFU_ID   1
#endif

#ifndef PM_NRF5340_DFU_SIZE
#define PM_NRF5340_DFU_SIZE (256 * 1024)
#endif
